//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.Answers = new HashSet<Answer>();
            this.exams = new HashSet<exam>();
            this.questions = new HashSet<question>();
            this.results = new HashSet<result>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<exam> exams { get; set; }
        public virtual ICollection<question> questions { get; set; }
        public virtual ICollection<result> results { get; set; }
    }
}
