//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class excenterdbContext : DbContext
    {
        public excenterdbContext()
            : base("name=excenterdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<course> courses { get; set; }
        public DbSet<evnt> evnts { get; set; }
        public DbSet<exam> exams { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<registration> registrations { get; set; }
        public DbSet<result> results { get; set; }
        public DbSet<user_info> user_info { get; set; }
    }
}
