//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int evnt_id { get; set; }
        public string user_name { get; set; }
        public int result { get; set; }
        public int ID { get; set; }
    
        public virtual evnt evnt { get; set; }
        public virtual user_info user_info { get; set; }
    }
}
