//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public user_info()
        {
            this.Answers = new HashSet<Answer>();
            this.registrations = new HashSet<registration>();
            this.results = new HashSet<result>();
        }
    
        public string user_name { get; set; }
        public string name { get; set; }
        public string user_type { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<registration> registrations { get; set; }
        public virtual ICollection<result> results { get; set; }
    }
}
